### ISSUE TITLE
Bug: Avoid mutating a prop directly

### ISSUE THREAD

**Issue by Bogatinovski** [quasarframework/app-extension-qmediaplayer#22] opened 2019-06-12 23:30 UTC
I have just installed the plugin and whenever I start playing a video I am getting the following error and a few warnings in the chrome console and they are all related to the loading spinner. Even though I am getting this errors the spinner is still appearing on the video player and seems to be working properly.

`vue.runtime.esm.js?2b0e:619 [Vue warn]: Error in callback for watcher "function () { return this._data.$$state }": "Error: [vuex] do not mutate vuex store state outside mutation handlers."

(found in <Root>)
warn @ vue.runtime.esm.js?2b0e:619
logError @ vue.runtime.esm.js?2b0e:1884
globalHandleError @ vue.runtime.esm.js?2b0e:1879
handleError @ vue.runtime.esm.js?2b0e:1839
run @ vue.runtime.esm.js?2b0e:4564
update @ vue.runtime.esm.js?2b0e:4536
notify @ vue.runtime.esm.js?2b0e:730
reactiveSetter @ vue.runtime.esm.js?2b0e:1055
(anonymous) @ Index.vue?b484:178
Promise.then (async)
playStream @ Index.vue?b484:176
click @ Index.vue?b5c3:169
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1854
invoker @ vue.runtime.esm.js?2b0e:2179
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1854
Vue.$emit @ vue.runtime.esm.js?2b0e:3882
Vue.<computed> @ backend.js:1140
__onClick @ QItem.js?6ab5:79
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1854
invoker @ vue.runtime.esm.js?2b0e:2179
original._wrapper @ vue.runtime.esm.js?2b0e:6911
vue.runtime.esm.js?2b0e:1888 Error: [vuex] do not mutate vuex store state outside mutation handlers.
    at assert (vuex.esm.js?2f62:87)
    at Vue.store._vm.$watch.deep (vuex.esm.js?2f62:763)
    at Watcher.run (vue.runtime.esm.js?2b0e:4562)
    at Watcher.update (vue.runtime.esm.js?2b0e:4536)
    at Dep.notify (vue.runtime.esm.js?2b0e:730)
    at Object.reactiveSetter [as PlayedAt] (vue.runtime.esm.js?2b0e:1055)
    at eval (Index.vue?b484:178)
logError @ vue.runtime.esm.js?2b0e:1888
globalHandleError @ vue.runtime.esm.js?2b0e:1879
handleError @ vue.runtime.esm.js?2b0e:1839
run @ vue.runtime.esm.js?2b0e:4564
update @ vue.runtime.esm.js?2b0e:4536
notify @ vue.runtime.esm.js?2b0e:730
reactiveSetter @ vue.runtime.esm.js?2b0e:1055
(anonymous) @ Index.vue?b484:178
Promise.then (async)
playStream @ Index.vue?b484:176
click @ Index.vue?b5c3:169
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1854
invoker @ vue.runtime.esm.js?2b0e:2179
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1854
Vue.$emit @ vue.runtime.esm.js?2b0e:3882
Vue.<computed> @ backend.js:1140
__onClick @ QItem.js?6ab5:79
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1854
invoker @ vue.runtime.esm.js?2b0e:2179
original._wrapper @ vue.runtime.esm.js?2b0e:6911
vue.runtime.esm.js?2b0e:619 [Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "spinnerSize"

found in

---> <QMediaPlayer>
       <QPage>
         <QPageContainer>
           <QLayout>
             <Player> at src/pages/player/Index.vue
               <App> at src/App.vue
                 <Root>
warn @ vue.runtime.esm.js?2b0e:619
(anonymous) @ vue.runtime.esm.js?2b0e:4672
reactiveSetter @ vue.runtime.esm.js?2b0e:1045
proxySetter @ vue.runtime.esm.js?2b0e:4625
__renderLoader @ QMediaPlayer.js?1c9f:1177
render @ QMediaPlayer.js?1c9f:1382
Vue._render @ vue.runtime.esm.js?2b0e:3542
updateComponent @ vue.runtime.esm.js?2b0e:4060
get @ vue.runtime.esm.js?2b0e:4473
run @ vue.runtime.esm.js?2b0e:4548
flushSchedulerQueue @ vue.runtime.esm.js?2b0e:4304
(anonymous) @ vue.runtime.esm.js?2b0e:1980
flushCallbacks @ vue.runtime.esm.js?2b0e:1906
Promise.then (async)
timerFunc @ vue.runtime.esm.js?2b0e:1933
nextTick @ vue.runtime.esm.js?2b0e:1990
queueWatcher @ vue.runtime.esm.js?2b0e:4396
update @ vue.runtime.esm.js?2b0e:4538
notify @ vue.runtime.esm.js?2b0e:730
reactiveSetter @ vue.runtime.esm.js?2b0e:1055
(anonymous) @ Index.vue?b484:178
Promise.then (async)
playStream @ Index.vue?b484:176
click @ Index.vue?b5c3:169
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1854
invoker @ vue.runtime.esm.js?2b0e:2179
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1854
Vue.$emit @ vue.runtime.esm.js?2b0e:3882
Vue.<computed> @ backend.js:1140
__onClick @ QItem.js?6ab5:79
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1854
invoker @ vue.runtime.esm.js?2b0e:2179
original._wrapper @ vue.runtime.esm.js?2b0e:6911
vue.runtime.esm.js?2b0e:619 [Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "spinnerSize"

found in

---> <QMediaPlayer>
       <QPage>
         <QPageContainer>
           <QLayout>
             <Player> at src/pages/player/Index.vue
               <App> at src/App.vue
                 <Root>`
I am sorry I don't know a better way to paste the error so here is a screenshot: 
![image](https://user-images.githubusercontent.com/7543902/59393083-5a2dfa80-8d7a-11e9-8c7b-432a758af9ed.png)

This is how I have initialized the  player: 
```
        <q-media-player
            v-if="video !== null"
            type="video"
            background-color="black"
            :autoplay="false"
            class="video-player"
            :dense="true"
            :show-big-play-button="true"
            :sources="video.sources"
            :poster="video.poster"
            @ended="onEnded"
          >
          </q-media-player>
```
and in the script section: 
```
    this.video = {
          label: stream.Title,
          poster: stream.Poster,
          sources: [
            {
              src: response.data.Url,
              type: 'video/mp4'
            }
          ]
        }
```

**Comment by hawkeye64** [comment] 2019-06-13 18:44
Can you tell me what version of QMediaPlayer you have? I believe this might be a duplicate of this issue: https://github.com/quasarframework/app-extension-qmediaplayer/issues/11, which was fixed in beta.15 - let me know.

**Comment by hawkeye64** [comment] 2019-06-13 18:55
Fixed in beta.17

**Closed by hawkeye64** 2019-06-13 18:55 UTC

**Comment by Bogatinovski** [comment] 2019-06-14 15:32
Thank you I appreciate it!
