### ISSUE TITLE
SSR fails to re-hydrate when initial `type` is 'video'

### ISSUE THREAD

**Issue by CheyenneForbes** [quasarframework/app-extension-qmediaplayer#11] opened 2019-06-02 02:01 UTC
my code:

```
<template>
     <q-media-player
          type="video"
          background-color="black"
          :muted="false"
          radius="1rem"
          :autoplay="true"
          :show-big-play-button="true"
          :sources="video.sources"
          :poster="video.poster"
          :tracks="video.tracks"
          track-language="English"
        >
          <template v-if="overlay" v-slot:overlay>
            <div>
              <img
                src="statics/logo.png"
                style="width: 30vw; max-width: 50px; opacity: 0.25;"
              >
            </div>
          </template>
        </q-media-player>
</template>

<style scoped>
</style>

<script>

export default {
  data () {
    return {
      video: [
        {
          label: 'Tears of Steel',
          poster: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/BigBuckBunny.jpg',
          sources: [
            {
              src: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
              type: 'video/mp4'
            }
          ],
          tracks: [
            {
              src: 'statics/media/TearsOfSteel/TOS-en.vtt',
              kind: 'subtitles',
              srclang: 'en',
              label: 'English'
            }
          ]
        }
      ]
    }
  }
}
</script>
```

browser console:

```
[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.
warn @ vue.runtime.esm.js?2b0e:619
patch @ vue.runtime.esm.js?2b0e:6491
Vue._update @ vue.runtime.esm.js?2b0e:3939
updateComponent @ vue.runtime.esm.js?2b0e:4060
get @ vue.runtime.esm.js?2b0e:4473
Watcher @ vue.runtime.esm.js?2b0e:4462
mountComponent @ vue.runtime.esm.js?2b0e:4067
Vue.$mount @ vue.runtime.esm.js?2b0e:8409
init @ vue.runtime.esm.js?2b0e:3118
hydrate @ vue.runtime.esm.js?2b0e:6372
hydrate @ vue.runtime.esm.js?2b0e:6405
hydrate @ vue.runtime.esm.js?2b0e:6405
patch @ vue.runtime.esm.js?2b0e:6487
Vue._update @ vue.runtime.esm.js?2b0e:3939
updateComponent @ vue.runtime.esm.js?2b0e:4060
get @ vue.runtime.esm.js?2b0e:4473
Watcher @ vue.runtime.esm.js?2b0e:4462
mountComponent @ vue.runtime.esm.js?2b0e:4067
Vue.$mount @ vue.runtime.esm.js?2b0e:8409
init @ vue.runtime.esm.js?2b0e:3118
hydrate @ vue.runtime.esm.js?2b0e:6372
hydrate @ vue.runtime.esm.js?2b0e:6405
hydrate @ vue.runtime.esm.js?2b0e:6405
hydrate @ vue.runtime.esm.js?2b0e:6405
hydrate @ vue.runtime.esm.js?2b0e:6405
patch @ vue.runtime.esm.js?2b0e:6487
Vue._update @ vue.runtime.esm.js?2b0e:3939
updateComponent @ vue.runtime.esm.js?2b0e:4060
get @ vue.runtime.esm.js?2b0e:4473
Watcher @ vue.runtime.esm.js?2b0e:4462
mountComponent @ vue.runtime.esm.js?2b0e:4067
Vue.$mount @ vue.runtime.esm.js?2b0e:8409
init @ vue.runtime.esm.js?2b0e:3118
hydrate @ vue.runtime.esm.js?2b0e:6372
hydrate @ vue.runtime.esm.js?2b0e:6405
hydrate @ vue.runtime.esm.js?2b0e:6405
hydrate @ vue.runtime.esm.js?2b0e:6405
patch @ vue.runtime.esm.js?2b0e:6487
Vue._update @ vue.runtime.esm.js?2b0e:3939
updateComponent @ vue.runtime.esm.js?2b0e:4060
get @ vue.runtime.esm.js?2b0e:4473
Watcher @ vue.runtime.esm.js?2b0e:4462
mountComponent @ vue.runtime.esm.js?2b0e:4067
Vue.$mount @ vue.runtime.esm.js?2b0e:8409
init @ vue.runtime.esm.js?2b0e:3118
hydrate @ vue.runtime.esm.js?2b0e:6372
patch @ vue.runtime.esm.js?2b0e:6487
Vue._update @ vue.runtime.esm.js?2b0e:3939
updateComponent @ vue.runtime.esm.js?2b0e:4060
get @ vue.runtime.esm.js?2b0e:4473
Watcher @ vue.runtime.esm.js?2b0e:4462
mountComponent @ vue.runtime.esm.js?2b0e:4067
Vue.$mount @ vue.runtime.esm.js?2b0e:8409
init @ vue.runtime.esm.js?2b0e:3118
merged @ vue.runtime.esm.js?2b0e:3301
hydrate @ vue.runtime.esm.js?2b0e:6372
hydrate @ vue.runtime.esm.js?2b0e:6405
patch @ vue.runtime.esm.js?2b0e:6487
Vue._update @ vue.runtime.esm.js?2b0e:3939
updateComponent @ vue.runtime.esm.js?2b0e:4060
get @ vue.runtime.esm.js?2b0e:4473
Watcher @ vue.runtime.esm.js?2b0e:4462
mountComponent @ vue.runtime.esm.js?2b0e:4067
Vue.$mount @ vue.runtime.esm.js?2b0e:8409
init @ vue.runtime.esm.js?2b0e:3118
hydrate @ vue.runtime.esm.js?2b0e:6372
patch @ vue.runtime.esm.js?2b0e:6487
Vue._update @ vue.runtime.esm.js?2b0e:3939
updateComponent @ vue.runtime.esm.js?2b0e:4060
get @ vue.runtime.esm.js?2b0e:4473
Watcher @ vue.runtime.esm.js?2b0e:4462
mountComponent @ vue.runtime.esm.js?2b0e:4067
Vue.$mount @ vue.runtime.esm.js?2b0e:8409
(anonymous) @ client-entry.js?2f39:111
(anonymous) @ vue-router.esm.js?8c4f:1898
(anonymous) @ vue-router.esm.js?8c4f:1898
(anonymous) @ vue-router.esm.js?8c4f:2000
step @ vue-router.esm.js?8c4f:1730
step @ vue-router.esm.js?8c4f:1737
step @ vue-router.esm.js?8c4f:1737
runQueue @ vue-router.esm.js?8c4f:1741
(anonymous) @ vue-router.esm.js?8c4f:1995
step @ vue-router.esm.js?8c4f:1730
(anonymous) @ vue-router.esm.js?8c4f:1734
(anonymous) @ vue-router.esm.js?8c4f:1980
(anonymous) @ vue-router.esm.js?8c4f:1773
(anonymous) @ vue-router.esm.js?8c4f:1849
Promise.then (async)
(anonymous) @ vue-router.esm.js?8c4f:1796
(anonymous) @ vue-router.esm.js?8c4f:1817
(anonymous) @ vue-router.esm.js?8c4f:1817
flatMapComponents @ vue-router.esm.js?8c4f:1816
(anonymous) @ vue-router.esm.js?8c4f:1752
iterator @ vue-router.esm.js?8c4f:1959
step @ vue-router.esm.js?8c4f:1733
step @ vue-router.esm.js?8c4f:1737
step @ vue-router.esm.js?8c4f:1737
runQueue @ vue-router.esm.js?8c4f:1741
confirmTransition @ vue-router.esm.js?8c4f:1988
transitionTo @ vue-router.esm.js?8c4f:1890
init @ vue-router.esm.js?8c4f:2541
beforeCreate @ vue-router.esm.js?8c4f:553
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1854
callHook @ vue.runtime.esm.js?2b0e:4213
Vue._init @ vue.runtime.esm.js?2b0e:4998
Vue @ vue.runtime.esm.js?2b0e:5079
_callee$ @ client-entry.js?2f39:105
tryCatch @ runtime.js?96cf:45
invoke @ runtime.js?96cf:271
prototype.<computed> @ runtime.js?96cf:97
asyncGeneratorStep @ asyncToGenerator.js?fa84:5
_next @ asyncToGenerator.js?fa84:27
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js?fa84:15
_next @ asyncToGenerator.js?fa84:27
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js?fa84:15
_next @ asyncToGenerator.js?fa84:27
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js?fa84:15
_next @ asyncToGenerator.js?fa84:27
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js?fa84:15
_next @ asyncToGenerator.js?fa84:27
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js?fa84:15
_next @ asyncToGenerator.js?fa84:27
(anonymous) @ asyncToGenerator.js?fa84:34
F @ _export.js?d13f:36
(anonymous) @ asyncToGenerator.js?fa84:23
_start @ client-entry.js?2f39:70
start @ client-entry.js?2f39:70
(anonymous) @ client-entry.js?2f39:118
./.quasar/client-entry.js @ app.js:929
__webpack_require__ @ app.js:767
fn @ app.js:130
0 @ app.js:8857
__webpack_require__ @ app.js:767
(anonymous) @ app.js:904
(anonymous) @ app.js:907
Show 57 more frames
vue.runtime.esm.js?2b0e:5861 Uncaught (in promise) TypeError: Cannot read property 'toLowerCase' of undefined
    at emptyNodeAt (vue.runtime.esm.js?2b0e:5861)
    at VueComponent.patch [as __patch__] (vue.runtime.esm.js?2b0e:6502)
    at VueComponent.Vue._update (vue.runtime.esm.js?2b0e:3939)
    at VueComponent.updateComponent (vue.runtime.esm.js?2b0e:4060)
    at Watcher.get (vue.runtime.esm.js?2b0e:4473)
    at new Watcher (vue.runtime.esm.js?2b0e:4462)
    at mountComponent (vue.runtime.esm.js?2b0e:4067)
    at VueComponent.Vue.$mount (vue.runtime.esm.js?2b0e:8409)
    at init (vue.runtime.esm.js?2b0e:3118)
    at hydrate (vue.runtime.esm.js?2b0e:6372)
```

**Comment by hawkeye64** [comment] 2019-06-04 15:39
You are building SSR and this error: "The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render." means your source vs what was rendered is not matching. Aka, hydration errors.

**Comment by CheyenneForbes** [comment] 2019-06-04 16:20
How is that possible? its not nesting in anything, its just as it is in the original comment

**Comment by hawkeye64** [comment] 2019-06-04 18:12
Not sure. I just built the demo (from the repo) in SSR mode and it is coming up fine. Maybe get the repo. run `yarn` in it. `cd demo`, run `yarn`. Then `quasar dev -m ssr` and see if it works out for you.

**Comment by CheyenneForbes** [comment] 2019-06-04 21:51
Does using just `<q-media-player></q-media-player>` without attributes give you the error? I get the same error when I try without attributes

**Comment by CheyenneForbes** [comment] 2019-06-05 10:43
When `type="audio"` all works well. After realizing this I also confirmed that setting `videoType` to `true` before building gives the same error and the video only works if you wait until it reaches the browser and toggle to video

**Comment by hawkeye64** [comment] 2019-06-05 13:38
So, when type="video", the SSR has hydration errors?

**Comment by CheyenneForbes** [comment] 2019-06-05 15:02
correct, it doesnt happen in SPA

**Comment by hawkeye64** [comment] 2019-06-06 20:42
Fixed in beta.14 - let me know how it works out for you. I'll leave this issue open for a bit.

**Comment by CheyenneForbes** [comment] 2019-06-07 04:56
It works ok now. Thanks

**Closed** 2019-06-07 17:37 UTC
